/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/_settings/route'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio/index'
import { Route as AppResultsIndexRouteImport } from './routes/_app/results/index'
import { Route as AuthenticatedStudioUploadRouteImport } from './routes/_authenticated/studio/upload'
import { Route as AppWatchIdIndexRouteImport } from './routes/_app/watch/$id.index'
import { Route as AppChannelAtChar123idChar125IndexRouteImport } from './routes/_app/_channel/@{$id}.index'
import { Route as AppSettingsSettingsNotificationsRouteImport } from './routes/_app/_settings/settings/notifications'
import { Route as AppSettingsSettingsAccountRouteImport } from './routes/_app/_settings/settings/account'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/_settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/_authenticated/studio/',
    path: '/studio/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppResultsIndexRoute = AppResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthenticatedStudioUploadRoute =
  AuthenticatedStudioUploadRouteImport.update({
    id: '/_authenticated/studio/upload',
    path: '/studio/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWatchIdIndexRoute = AppWatchIdIndexRouteImport.update({
  id: '/watch/$id/',
  path: '/watch/$id/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChannelAtChar123idChar125IndexRoute =
  AppChannelAtChar123idChar125IndexRouteImport.update({
    id: '/_channel/@{$id}/',
    path: '/@{$id}/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSettingsSettingsNotificationsRoute =
  AppSettingsSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsSettingsAccountRoute =
  AppSettingsSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/studio/upload': typeof AuthenticatedStudioUploadRoute
  '/results/': typeof AppResultsIndexRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
  '/settings/account': typeof AppSettingsSettingsAccountRoute
  '/settings/notifications': typeof AppSettingsSettingsNotificationsRoute
  '/@{$id}/': typeof AppChannelAtChar123idChar125IndexRoute
  '/watch/$id/': typeof AppWatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/studio/upload': typeof AuthenticatedStudioUploadRoute
  '/results': typeof AppResultsIndexRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
  '/settings/account': typeof AppSettingsSettingsAccountRoute
  '/settings/notifications': typeof AppSettingsSettingsNotificationsRoute
  '/@{$id}': typeof AppChannelAtChar123idChar125IndexRoute
  '/watch/$id': typeof AppWatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/_settings': typeof AppSettingsRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_authenticated/studio/upload': typeof AuthenticatedStudioUploadRoute
  '/_app/results/': typeof AppResultsIndexRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
  '/_app/_settings/settings/account': typeof AppSettingsSettingsAccountRoute
  '/_app/_settings/settings/notifications': typeof AppSettingsSettingsNotificationsRoute
  '/_app/_channel/@{$id}/': typeof AppChannelAtChar123idChar125IndexRoute
  '/_app/watch/$id/': typeof AppWatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/api/$'
    | '/studio/upload'
    | '/results/'
    | '/studio/'
    | '/settings/account'
    | '/settings/notifications'
    | '/@{$id}/'
    | '/watch/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/$'
    | '/studio/upload'
    | '/results'
    | '/studio'
    | '/settings/account'
    | '/settings/notifications'
    | '/@{$id}'
    | '/watch/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_settings'
    | '/_auth/login'
    | '/_auth/signup'
    | '/api/$'
    | '/_app/'
    | '/_authenticated/studio/upload'
    | '/_app/results/'
    | '/_authenticated/studio/'
    | '/_app/_settings/settings/account'
    | '/_app/_settings/settings/notifications'
    | '/_app/_channel/@{$id}/'
    | '/_app/watch/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthenticatedStudioUploadRoute: typeof AuthenticatedStudioUploadRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_settings': {
      id: '/_app/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/results/': {
      id: '/_app/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof AppResultsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_authenticated/studio/upload': {
      id: '/_authenticated/studio/upload'
      path: '/studio/upload'
      fullPath: '/studio/upload'
      preLoaderRoute: typeof AuthenticatedStudioUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/watch/$id/': {
      id: '/_app/watch/$id/'
      path: '/watch/$id'
      fullPath: '/watch/$id/'
      preLoaderRoute: typeof AppWatchIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_channel/@{$id}/': {
      id: '/_app/_channel/@{$id}/'
      path: '/@{$id}'
      fullPath: '/@{$id}/'
      preLoaderRoute: typeof AppChannelAtChar123idChar125IndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_settings/settings/notifications': {
      id: '/_app/_settings/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/_settings/settings/account': {
      id: '/_app/_settings/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsSettingsAccountRoute: typeof AppSettingsSettingsAccountRoute
  AppSettingsSettingsNotificationsRoute: typeof AppSettingsSettingsNotificationsRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsSettingsAccountRoute: AppSettingsSettingsAccountRoute,
  AppSettingsSettingsNotificationsRoute: AppSettingsSettingsNotificationsRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppResultsIndexRoute: typeof AppResultsIndexRoute
  AppChannelAtChar123idChar125IndexRoute: typeof AppChannelAtChar123idChar125IndexRoute
  AppWatchIdIndexRoute: typeof AppWatchIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppResultsIndexRoute: AppResultsIndexRoute,
  AppChannelAtChar123idChar125IndexRoute:
    AppChannelAtChar123idChar125IndexRoute,
  AppWatchIdIndexRoute: AppWatchIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthenticatedStudioUploadRoute: AuthenticatedStudioUploadRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
