/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio/index'
import { Route as AppTestIndexRouteImport } from './routes/_app/test/index'
import { Route as AppResultsIndexRouteImport } from './routes/_app/results/index'
import { Route as AppChannelIndexRouteImport } from './routes/_app/channel/index'
import { Route as AuthenticatedStudioUploadRouteImport } from './routes/_authenticated/studio/upload'
import { Route as AppWatchIdIndexRouteImport } from './routes/_app/watch/$id.index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/_authenticated/studio/',
    path: '/studio/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppTestIndexRoute = AppTestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppResultsIndexRoute = AppResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChannelIndexRoute = AppChannelIndexRouteImport.update({
  id: '/channel/',
  path: '/channel/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthenticatedStudioUploadRoute =
  AuthenticatedStudioUploadRouteImport.update({
    id: '/_authenticated/studio/upload',
    path: '/studio/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWatchIdIndexRoute = AppWatchIdIndexRouteImport.update({
  id: '/watch/$id/',
  path: '/watch/$id/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/studio/upload': typeof AuthenticatedStudioUploadRoute
  '/channel/': typeof AppChannelIndexRoute
  '/results/': typeof AppResultsIndexRoute
  '/test/': typeof AppTestIndexRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
  '/watch/$id/': typeof AppWatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof AppIndexRoute
  '/studio/upload': typeof AuthenticatedStudioUploadRoute
  '/channel': typeof AppChannelIndexRoute
  '/results': typeof AppResultsIndexRoute
  '/test': typeof AppTestIndexRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
  '/watch/$id': typeof AppWatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_authenticated/studio/upload': typeof AuthenticatedStudioUploadRoute
  '/_app/channel/': typeof AppChannelIndexRoute
  '/_app/results/': typeof AppResultsIndexRoute
  '/_app/test/': typeof AppTestIndexRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
  '/_app/watch/$id/': typeof AppWatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/api/$'
    | '/studio/upload'
    | '/channel/'
    | '/results/'
    | '/test/'
    | '/studio/'
    | '/watch/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/api/$'
    | '/'
    | '/studio/upload'
    | '/channel'
    | '/results'
    | '/test'
    | '/studio'
    | '/watch/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_auth/login'
    | '/_auth/signup'
    | '/api/$'
    | '/_app/'
    | '/_authenticated/studio/upload'
    | '/_app/channel/'
    | '/_app/results/'
    | '/_app/test/'
    | '/_authenticated/studio/'
    | '/_app/watch/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthenticatedStudioUploadRoute: typeof AuthenticatedStudioUploadRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/test/': {
      id: '/_app/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof AppTestIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/results/': {
      id: '/_app/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof AppResultsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/channel/': {
      id: '/_app/channel/'
      path: '/channel'
      fullPath: '/channel/'
      preLoaderRoute: typeof AppChannelIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_authenticated/studio/upload': {
      id: '/_authenticated/studio/upload'
      path: '/studio/upload'
      fullPath: '/studio/upload'
      preLoaderRoute: typeof AuthenticatedStudioUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/watch/$id/': {
      id: '/_app/watch/$id/'
      path: '/watch/$id'
      fullPath: '/watch/$id/'
      preLoaderRoute: typeof AppWatchIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppChannelIndexRoute: typeof AppChannelIndexRoute
  AppResultsIndexRoute: typeof AppResultsIndexRoute
  AppTestIndexRoute: typeof AppTestIndexRoute
  AppWatchIdIndexRoute: typeof AppWatchIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppChannelIndexRoute: AppChannelIndexRoute,
  AppResultsIndexRoute: AppResultsIndexRoute,
  AppTestIndexRoute: AppTestIndexRoute,
  AppWatchIdIndexRoute: AppWatchIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthenticatedStudioUploadRoute: AuthenticatedStudioUploadRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
