/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppResultsIndexRouteImport } from './routes/_app/results/index'
import { Route as AppChannelIndexRouteImport } from './routes/_app/channel/index'
import { Route as AuthenticatedStudioUploadRouteImport } from './routes/_authenticated/studio/upload'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings/notifications'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppWatchIdIndexRouteImport } from './routes/_app/watch/$id.index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/_authenticated/studio/',
    path: '/studio/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppResultsIndexRoute = AppResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChannelIndexRoute = AppChannelIndexRouteImport.update({
  id: '/channel/',
  path: '/channel/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthenticatedStudioUploadRoute =
  AuthenticatedStudioUploadRouteImport.update({
    id: '/_authenticated/studio/upload',
    path: '/studio/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppWatchIdIndexRoute = AppWatchIdIndexRouteImport.update({
  id: '/watch/$id/',
  path: '/watch/$id/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/studio/upload': typeof AuthenticatedStudioUploadRoute
  '/channel/': typeof AppChannelIndexRoute
  '/results/': typeof AppResultsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
  '/watch/$id/': typeof AppWatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof AppIndexRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/studio/upload': typeof AuthenticatedStudioUploadRoute
  '/channel': typeof AppChannelIndexRoute
  '/results': typeof AppResultsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
  '/watch/$id': typeof AppWatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_authenticated/studio/upload': typeof AuthenticatedStudioUploadRoute
  '/_app/channel/': typeof AppChannelIndexRoute
  '/_app/results/': typeof AppResultsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
  '/_app/watch/$id/': typeof AppWatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/signup'
    | '/api/$'
    | '/settings/account'
    | '/settings/notifications'
    | '/studio/upload'
    | '/channel/'
    | '/results/'
    | '/settings/'
    | '/studio/'
    | '/watch/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/api/$'
    | '/'
    | '/settings/account'
    | '/settings/notifications'
    | '/studio/upload'
    | '/channel'
    | '/results'
    | '/settings'
    | '/studio'
    | '/watch/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/settings'
    | '/_auth/login'
    | '/_auth/signup'
    | '/api/$'
    | '/_app/'
    | '/_app/settings/account'
    | '/_app/settings/notifications'
    | '/_authenticated/studio/upload'
    | '/_app/channel/'
    | '/_app/results/'
    | '/_app/settings/'
    | '/_authenticated/studio/'
    | '/_app/watch/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthenticatedStudioUploadRoute: typeof AuthenticatedStudioUploadRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/results/': {
      id: '/_app/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof AppResultsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/channel/': {
      id: '/_app/channel/'
      path: '/channel'
      fullPath: '/channel/'
      preLoaderRoute: typeof AppChannelIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_authenticated/studio/upload': {
      id: '/_authenticated/studio/upload'
      path: '/studio/upload'
      fullPath: '/studio/upload'
      preLoaderRoute: typeof AuthenticatedStudioUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/watch/$id/': {
      id: '/_app/watch/$id/'
      path: '/watch/$id'
      fullPath: '/watch/$id/'
      preLoaderRoute: typeof AppWatchIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppChannelIndexRoute: typeof AppChannelIndexRoute
  AppResultsIndexRoute: typeof AppResultsIndexRoute
  AppWatchIdIndexRoute: typeof AppWatchIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppChannelIndexRoute: AppChannelIndexRoute,
  AppResultsIndexRoute: AppResultsIndexRoute,
  AppWatchIdIndexRoute: AppWatchIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthenticatedStudioUploadRoute: AuthenticatedStudioUploadRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
