/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/_settings/route'
import { Route as AppResultsIndexRouteImport } from './routes/_app/results/index'
import { Route as StudioStudioChannelIdRouteRouteImport } from './routes/_studio/studio/$channelId/route'
import { Route as StudioStudioChannelIdIndexRouteImport } from './routes/_studio/studio/$channelId/index'
import { Route as AppWatchIdIndexRouteImport } from './routes/_app/watch/$id.index'
import { Route as AppChannelAtChar123idChar125IndexRouteImport } from './routes/_app/_channel/@{$id}.index'
import { Route as AppSettingsSettingsNotificationsRouteImport } from './routes/_app/_settings/settings/notifications'
import { Route as AppSettingsSettingsAccountRouteImport } from './routes/_app/_settings/settings/account'
import { Route as StudioStudioChannelIdContentRouteRouteImport } from './routes/_studio/studio/$channelId/_content/route'
import { Route as StudioStudioChannelIdContentContentVideosRouteImport } from './routes/_studio/studio/$channelId/_content/content/videos'
import { Route as StudioStudioChannelIdContentContentPlaylistsRouteImport } from './routes/_studio/studio/$channelId/_content/content/playlists'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/_settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppResultsIndexRoute = AppResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => AppRouteRoute,
} as any)
const StudioStudioChannelIdRouteRoute =
  StudioStudioChannelIdRouteRouteImport.update({
    id: '/_studio/studio/$channelId',
    path: '/studio/$channelId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudioStudioChannelIdIndexRoute =
  StudioStudioChannelIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudioStudioChannelIdRouteRoute,
  } as any)
const AppWatchIdIndexRoute = AppWatchIdIndexRouteImport.update({
  id: '/watch/$id/',
  path: '/watch/$id/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChannelAtChar123idChar125IndexRoute =
  AppChannelAtChar123idChar125IndexRouteImport.update({
    id: '/_channel/@{$id}/',
    path: '/@{$id}/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSettingsSettingsNotificationsRoute =
  AppSettingsSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsSettingsAccountRoute =
  AppSettingsSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const StudioStudioChannelIdContentRouteRoute =
  StudioStudioChannelIdContentRouteRouteImport.update({
    id: '/_content',
    getParentRoute: () => StudioStudioChannelIdRouteRoute,
  } as any)
const StudioStudioChannelIdContentContentVideosRoute =
  StudioStudioChannelIdContentContentVideosRouteImport.update({
    id: '/content/videos',
    path: '/content/videos',
    getParentRoute: () => StudioStudioChannelIdContentRouteRoute,
  } as any)
const StudioStudioChannelIdContentContentPlaylistsRoute =
  StudioStudioChannelIdContentContentPlaylistsRouteImport.update({
    id: '/content/playlists',
    path: '/content/playlists',
    getParentRoute: () => StudioStudioChannelIdContentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/studio/$channelId': typeof StudioStudioChannelIdContentRouteRouteWithChildren
  '/results/': typeof AppResultsIndexRoute
  '/settings/account': typeof AppSettingsSettingsAccountRoute
  '/settings/notifications': typeof AppSettingsSettingsNotificationsRoute
  '/@{$id}/': typeof AppChannelAtChar123idChar125IndexRoute
  '/watch/$id/': typeof AppWatchIdIndexRoute
  '/studio/$channelId/': typeof StudioStudioChannelIdIndexRoute
  '/studio/$channelId/content/playlists': typeof StudioStudioChannelIdContentContentPlaylistsRoute
  '/studio/$channelId/content/videos': typeof StudioStudioChannelIdContentContentVideosRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/results': typeof AppResultsIndexRoute
  '/studio/$channelId': typeof StudioStudioChannelIdIndexRoute
  '/settings/account': typeof AppSettingsSettingsAccountRoute
  '/settings/notifications': typeof AppSettingsSettingsNotificationsRoute
  '/@{$id}': typeof AppChannelAtChar123idChar125IndexRoute
  '/watch/$id': typeof AppWatchIdIndexRoute
  '/studio/$channelId/content/playlists': typeof StudioStudioChannelIdContentContentPlaylistsRoute
  '/studio/$channelId/content/videos': typeof StudioStudioChannelIdContentContentVideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/_settings': typeof AppSettingsRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_studio/studio/$channelId': typeof StudioStudioChannelIdRouteRouteWithChildren
  '/_app/results/': typeof AppResultsIndexRoute
  '/_studio/studio/$channelId/_content': typeof StudioStudioChannelIdContentRouteRouteWithChildren
  '/_app/_settings/settings/account': typeof AppSettingsSettingsAccountRoute
  '/_app/_settings/settings/notifications': typeof AppSettingsSettingsNotificationsRoute
  '/_app/_channel/@{$id}/': typeof AppChannelAtChar123idChar125IndexRoute
  '/_app/watch/$id/': typeof AppWatchIdIndexRoute
  '/_studio/studio/$channelId/': typeof StudioStudioChannelIdIndexRoute
  '/_studio/studio/$channelId/_content/content/playlists': typeof StudioStudioChannelIdContentContentPlaylistsRoute
  '/_studio/studio/$channelId/_content/content/videos': typeof StudioStudioChannelIdContentContentVideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/studio/$channelId'
    | '/results/'
    | '/settings/account'
    | '/settings/notifications'
    | '/@{$id}/'
    | '/watch/$id/'
    | '/studio/$channelId/'
    | '/studio/$channelId/content/playlists'
    | '/studio/$channelId/content/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/results'
    | '/studio/$channelId'
    | '/settings/account'
    | '/settings/notifications'
    | '/@{$id}'
    | '/watch/$id'
    | '/studio/$channelId/content/playlists'
    | '/studio/$channelId/content/videos'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_settings'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/'
    | '/_studio/studio/$channelId'
    | '/_app/results/'
    | '/_studio/studio/$channelId/_content'
    | '/_app/_settings/settings/account'
    | '/_app/_settings/settings/notifications'
    | '/_app/_channel/@{$id}/'
    | '/_app/watch/$id/'
    | '/_studio/studio/$channelId/'
    | '/_studio/studio/$channelId/_content/content/playlists'
    | '/_studio/studio/$channelId/_content/content/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  StudioStudioChannelIdRouteRoute: typeof StudioStudioChannelIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_settings': {
      id: '/_app/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/results/': {
      id: '/_app/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof AppResultsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_studio/studio/$channelId': {
      id: '/_studio/studio/$channelId'
      path: '/studio/$channelId'
      fullPath: '/studio/$channelId'
      preLoaderRoute: typeof StudioStudioChannelIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/studio/$channelId/': {
      id: '/_studio/studio/$channelId/'
      path: '/'
      fullPath: '/studio/$channelId/'
      preLoaderRoute: typeof StudioStudioChannelIdIndexRouteImport
      parentRoute: typeof StudioStudioChannelIdRouteRoute
    }
    '/_app/watch/$id/': {
      id: '/_app/watch/$id/'
      path: '/watch/$id'
      fullPath: '/watch/$id/'
      preLoaderRoute: typeof AppWatchIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_channel/@{$id}/': {
      id: '/_app/_channel/@{$id}/'
      path: '/@{$id}'
      fullPath: '/@{$id}/'
      preLoaderRoute: typeof AppChannelAtChar123idChar125IndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_settings/settings/notifications': {
      id: '/_app/_settings/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/_settings/settings/account': {
      id: '/_app/_settings/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_studio/studio/$channelId/_content': {
      id: '/_studio/studio/$channelId/_content'
      path: ''
      fullPath: '/studio/$channelId'
      preLoaderRoute: typeof StudioStudioChannelIdContentRouteRouteImport
      parentRoute: typeof StudioStudioChannelIdRouteRoute
    }
    '/_studio/studio/$channelId/_content/content/videos': {
      id: '/_studio/studio/$channelId/_content/content/videos'
      path: '/content/videos'
      fullPath: '/studio/$channelId/content/videos'
      preLoaderRoute: typeof StudioStudioChannelIdContentContentVideosRouteImport
      parentRoute: typeof StudioStudioChannelIdContentRouteRoute
    }
    '/_studio/studio/$channelId/_content/content/playlists': {
      id: '/_studio/studio/$channelId/_content/content/playlists'
      path: '/content/playlists'
      fullPath: '/studio/$channelId/content/playlists'
      preLoaderRoute: typeof StudioStudioChannelIdContentContentPlaylistsRouteImport
      parentRoute: typeof StudioStudioChannelIdContentRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsSettingsAccountRoute: typeof AppSettingsSettingsAccountRoute
  AppSettingsSettingsNotificationsRoute: typeof AppSettingsSettingsNotificationsRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsSettingsAccountRoute: AppSettingsSettingsAccountRoute,
  AppSettingsSettingsNotificationsRoute: AppSettingsSettingsNotificationsRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppResultsIndexRoute: typeof AppResultsIndexRoute
  AppChannelAtChar123idChar125IndexRoute: typeof AppChannelAtChar123idChar125IndexRoute
  AppWatchIdIndexRoute: typeof AppWatchIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppResultsIndexRoute: AppResultsIndexRoute,
  AppChannelAtChar123idChar125IndexRoute:
    AppChannelAtChar123idChar125IndexRoute,
  AppWatchIdIndexRoute: AppWatchIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface StudioStudioChannelIdContentRouteRouteChildren {
  StudioStudioChannelIdContentContentPlaylistsRoute: typeof StudioStudioChannelIdContentContentPlaylistsRoute
  StudioStudioChannelIdContentContentVideosRoute: typeof StudioStudioChannelIdContentContentVideosRoute
}

const StudioStudioChannelIdContentRouteRouteChildren: StudioStudioChannelIdContentRouteRouteChildren =
  {
    StudioStudioChannelIdContentContentPlaylistsRoute:
      StudioStudioChannelIdContentContentPlaylistsRoute,
    StudioStudioChannelIdContentContentVideosRoute:
      StudioStudioChannelIdContentContentVideosRoute,
  }

const StudioStudioChannelIdContentRouteRouteWithChildren =
  StudioStudioChannelIdContentRouteRoute._addFileChildren(
    StudioStudioChannelIdContentRouteRouteChildren,
  )

interface StudioStudioChannelIdRouteRouteChildren {
  StudioStudioChannelIdContentRouteRoute: typeof StudioStudioChannelIdContentRouteRouteWithChildren
  StudioStudioChannelIdIndexRoute: typeof StudioStudioChannelIdIndexRoute
}

const StudioStudioChannelIdRouteRouteChildren: StudioStudioChannelIdRouteRouteChildren =
  {
    StudioStudioChannelIdContentRouteRoute:
      StudioStudioChannelIdContentRouteRouteWithChildren,
    StudioStudioChannelIdIndexRoute: StudioStudioChannelIdIndexRoute,
  }

const StudioStudioChannelIdRouteRouteWithChildren =
  StudioStudioChannelIdRouteRoute._addFileChildren(
    StudioStudioChannelIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  StudioStudioChannelIdRouteRoute: StudioStudioChannelIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
